apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: deansorie@deanosaur.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          route53:
            hostedZoneID: Z037973612K2BDV6YLPWW
            region: eu-west-1
        selector:
          dnsZones:
            - "cicd.deanosaur.com"
      - http01:
          ingress:
            class: nginx
