apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.frontend.service.name }}"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: cicd.deanosaur.com
spec:
  ports:
    - port: 80
      targetPort: 3001
  selector:
    app: "{{ .Values.frontend.deploy.name }}"
  type: "{{ .Values.frontend.service.type }}"
