apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - cicd.deanosaur.com
      secretName: todo-app-tls
  rules:
    - host: cicd.deanosaur.com
      http:
        paths:
          - path: /todos
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 80
          - path: /todos/:id
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
